minimal/note/models.py
from __future__ import absolute_import

import datetime

from minimal.ext import db


class Note(db.Model):
    id_ = db.Column(db.Integer(), primary_key=True)
    content = db.Column(db.UnicodeText())
    updated_at = db.Column(db.DateTime())
    created_at = db.Column(db.DateTime(), default=datetime.datetime.utcnow)

    def make_summary(self, max_length=20):
        if len(self.content) > max_length:
            return u'{0} ...'.format(self.content[:max_length + 1])
        return self.content

    @classmethod
    def get_multi(cls, limit=10, offset=0):
        return db.session.query(cls).limit(limit).offset(offset).all()

    def save(self):
        self.updated_at = datetime.datetime.utcnow()
        db.session.add(self)
        db.session.commit()

minimal/note/forms.py
from __future__ import absolute_import

from flask_wtf import FlaskForm
from wtforms import fields, validators


class NewNoteForm(FlaskForm):
    content = fields.TextAreaField(u'Content', validators=[
        validators.DataRequired(u'Content is required.'),
    ])
    submit = fields.SubmitField(u'Add It')

minimal/__init__.py
from __future__ import absolute_import

minimal/app.py
from __future__ import absolute_import

from flask import Flask

from minimal.ext import db
from minimal.note.views import bp as note_bp


def create_app():
    app = Flask(__name__)
    app.config.from_object('envcfg.smart.minimal')

    # extensions
    db.init_app(app)

    # blueprints
    app.register_blueprint(note_bp)

    return app

minimal/note/__init__.py
from __future__ import absolute_import

minimal/note/views.py
from __future__ import absolute_import

from flask import Blueprint, request, redirect, render_template, url_for, flash

from minimal.note.forms import NewNoteForm
from minimal.note.models import Note
from minimal.note.utils import to_timestamp


bp = Blueprint('note', __name__, url_prefix='/note')


@bp.route('/')
def index():
    offset = request.args.get('offset', type=int, default=0)
    form = NewNoteForm()
    notes = [
        {
            'id': note.id_,
            'summary': note.make_summary(),
            'updated_at': to_timestamp(note.updated_at),
            'created_at': to_timestamp(note.created_at),
        }
        for note in Note.get_multi(limit=20, offset=offset)
    ]
    return render_template('note/index.html', form=form, notes=notes)


@bp.route('/new', methods=['POST'])
def new():
    form = NewNoteForm()
    if form.validate_on_submit():
        note = Note(content=form.content.data)
        note.save()
    else:
        flash(u'error: {0}'.format(form.errors))
    return redirect(url_for('note.index'))

minimal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ page_title | default('Home') }} - Minimal</title>
  {% block page_header %}
  {% endblock %}
</head>
<body>
  {% block page_message %}
    {% for message in get_flashed_messages() %}
      <span>{{ message }}</span>
    {% endfor %}
  {% endblock %}
  {% block page_content %}
  {% endblock %}
</body>
</html>

minimal/templates/note/index.html
{% extends 'base.html' %}

{% block page_header %}
{% endblock %}

{% block page_content %}
  <form action="{{ url_for('note.new') }}" method="POST">
    {{ form.csrf_token() }}
    <div class="cx-form-line">
      {{ form.content.label(class='cx-form-label') }}
      {{ form.content(class='cx-form-input') }}
    </div>
    <div class="cx-form-action">
      {{ form.submit(class='cx-form-button') }}
    </div>
  </form>

  <ul class="cx-note-list">
    {% for note in notes %}
    <li id="#note-{{ note.id }}">
      <p>{{ note.summary }}</p>
      <span>updated_at: {{ note.updated_at }}</span>
      <span>created_at: {{ note.created_at }}</span>
    </li>
    {% endfor %}
  </ul>
{% endblock %}